gemfile: Gemfile

PreCommit:
  ExecutePermissions:
    enabled: true
    exclude:
      - 'bin/marina'

  HardTabs:
    enabled: true

  RuboCop:
    enabled: true
    command: ['bundle', 'exec', 'rubocop']

  TrailingWhitespace:
    enabled: true

  YamlSyntax:
    enabled: true
